//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp9
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int id { get; set; }
        public Nullable<int> id_good { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_manager { get; set; }
        public Nullable<int> cnt { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
    
        public virtual good good { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
